# -*- coding: utf-8 -*-
"""Script_Focos_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDkC_Ojv_rzLUyySt6yl0xBcj6Xcl8do
"""

"""
Código complementar para reprodução da metodologia apresentada em:

"Conflitos de uso da terra e vulnerabilidade ao fogo na APA do Rio Uberaba"

Este script apresenta uma versão simplificada e organizada dos procedimentos
computacionais descritos no manuscrito. São reproduzidas as principais etapas
de preparação dos dados, identificação das áreas de conflito, processamento
dos focos de calor, análise do gradiente espacial, correlações estatísticas
e análise da precipitação.

Os dados utilizados são provenientes de bases públicas indicadas no manuscrito.
Os focos de calor utilizados nas análises foram previamente obtidos das bases
públicas do Programa Queimadas/INPE e armazenados localmente para posterior
processamento pelo código. O script não realiza o download automático desses
dados.

Principais fontes de dados:

- INPE – Programa Queimadas:
  https://data.inpe.br/queimadas/

- MapBiomas – Projeto MapBiomas:
  https://brasil.mapbiomas.org/

- EMBRAPA – Solos e informações de aptidão agrícola:
  https://www.embrapa.br/solos

- CHIRPS – Climate Hazards Center:
  https://www.chc.ucsb.edu/data/chirps

Os caminhos dos arquivos devem ser definidos pelo usuário conforme a estrutura
local de armazenamento dos dados.

O código pode ser executado em ambiente Python, incluindo o Google Colab,
desde que sejam instaladas as bibliotecas necessárias e, quando aplicável,
seja realizada a autenticação e inicialização da API do Google Earth Engine.
Os procedimentos que dependem de dados ou operações disponibilizados pelo
Google Earth Engine requerem uma conta habilitada para utilização da API.

O código foi organizado para fins de transparência metodológica e
reprodutibilidade dos procedimentos analíticos, não constituindo o código
integral de desenvolvimento utilizado durante a pesquisa.
"""

# ============================================================
# 1. IMPORTS E INICIALIZAÇÃO
# ============================================================
import os
import glob
from pathlib import Path
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr, spearmanr
import ee
import geemap
from shapely.geometry import shape

# Autenticação do Google Earth Engine (necessita conta GEE ativa)
# Substitua 'seu-projeto-gee' pelo ID do seu projeto no Google Cloud
ee.Authenticate()
ee.Initialize(project='seu-projeto-gee')

# ============================================================
# 2. DEFINIÇÃO DE DIRETÓRIOS E CONFIGURAÇÕES
# ============================================================
# O usuário deve definir os caminhos locais contendo os dados brutos
DIRETORIO_ENTRADA = Path('./dados/entrada')
DIRETORIO_SAIDA = Path('./dados/saida')
DIRETORIO_SAIDA.mkdir(parents=True, exist_ok=True)

anos_estudo = list(range(2013, 2024))
distancias_buffer = list(range(100, 1001, 100)) # 100 a 1000m (passo de 100)

# Configurações de plotagem
sns.set_style("ticks")
plt.rcParams.update({'font.family': 'sans-serif', 'font.size': 10})

# ============================================================
# 3. BASE DE DADOS GEE E MODELAGEM DE CONFLITOS
# ============================================================
# Caminhos para os assets no GEE (Substituir pelos IDs públicos ou do seu repositório)
ASSET_AREA_ESTUDO = 'caminho/para/asset/area_estudo'
ASSET_APTIDAO = 'caminho/para/asset/aptidao_agricola'
ASSET_MAPBIOMAS = 'projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_integration_v1'

area_estudo = ee.FeatureCollection(ASSET_AREA_ESTUDO)
area_shape = shape(geemap.ee_to_geojson(area_estudo.geometry()))
mapbiomas = ee.Image(ASSET_MAPBIOMAS)
aptidao = ee.Image(ASSET_APTIDAO).rename('aptidao')

# Reclassificação MapBiomas para uso do solo (simplificado conforme metodologia)
old_values = [20, 39, 40, 41, 46, 47, 48, 15, 21, 3, 4, 11, 12, 9, 24, 30, 33]
new_values = [1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 0, 0, 0]

def gerar_conflito_ano(ano):
    """Calcula o conflito (Aptidão - Uso do Solo) para um determinado ano."""
    uso_reclass = mapbiomas.select(f'classification_{ano}').remap(old_values, new_values).rename('uso_reclass')
    return aptidao.subtract(uso_reclass).rename('conflito').clip(area_estudo)

# ============================================================
# 4. PROCESSAMENTO DOS FOCOS DE CALOR
# ============================================================
# Carregamento dos dados do BDQueimadas (INPE)
arquivos_focos = glob.glob(f'{DIRETORIO_ENTRADA}/focos_br_mg_*.csv')
df_focos = pd.concat([pd.read_csv(f, sep=',', encoding='latin1') for f in arquivos_focos], ignore_index=True)
gdf_focos = gpd.GeoDataFrame(df_focos, geometry=gpd.points_from_xy(df_focos['lon'], df_focos['lat']), crs='EPSG:4326')

# Filtro espacial (dentro da APA) e temporal
gdf_focos = gdf_focos[gdf_focos.geometry.within(area_shape)].copy()
gdf_focos['data_pas'] = pd.to_datetime(gdf_focos['data_pas']).dt.date
gdf_focos['ano'] = pd.to_datetime(gdf_focos['data_pas']).dt.year
gdf_focos = gdf_focos[gdf_focos['ano'].isin(anos_estudo)][['ano', 'data_pas', 'lat', 'lon', 'geometry']]

# Reprojeção para métrica (SIRGAS 2000 UTM 23S, ajustar EPSG se necessário)
gdf_focos_metrico = gdf_focos.to_crs('EPSG:31983').copy()
gdf_focos_metrico['distancia_conflito_m'] = np.nan
gdf_focos_metrico['conflito_local'] = 0

# ============================================================
# 5. DINÂMICA ANUAL: CONFLITOS E CÁLCULO DE DISTÂNCIAS
# ============================================================
areas_aneis_anuais = []
conflitos_anuais_geom = {}

for ano in anos_estudo:
    img_conflito = gerar_conflito_ano(ano)

    # Extrair áreas de conflito (Classes 1 e 2 indicam conflito real)
    vetores_conflito = img_conflito.eq(1).Or(img_conflito.eq(2)).selfMask().reduceToVectors(
        geometry=area_estudo.geometry(), scale=30, geometryType='polygon', eightConnected=True, maxPixels=1e10
    )

    try:
        gdf_conf = geemap.ee_to_gdf(vetores_conflito)
        if gdf_conf.crs is None: gdf_conf = gdf_conf.set_crs('EPSG:4326')
        geom_conflito = gdf_conf.to_crs('EPSG:31983').geometry.union_all()
        conflitos_anuais_geom[ano] = geom_conflito

        # Criação dos anéis concêntricos (buffers) para cálculo de área
        areas_aneis_anuais.append({'ano': ano, 'classe': 'Dentro do conflito', 'area_km2': geom_conflito.area / 1e6})
        buf_ant = geom_conflito
        for d in distancias_buffer:
            buf_atual = geom_conflito.buffer(d)
            classe_nome = '0–100 m' if d == 100 else f'{d-100}–{d} m'
            areas_aneis_anuais.append({'ano': ano, 'classe': classe_nome, 'area_km2': (buf_atual.difference(buf_ant)).area / 1e6})
            buf_ant = buf_atual

    except Exception as e:
        print(f"Erro ao processar vetores do ano {ano}: {e}")
        continue

    # Distância dos focos às áreas de conflito do mesmo ano
    mask_ano = gdf_focos_metrico['ano'] == ano
    if mask_ano.sum() > 0 and ano in conflitos_anuais_geom:
        focos_ano = gdf_focos_metrico.loc[mask_ano]
        gdf_focos_metrico.loc[mask_ano, 'distancia_conflito_m'] = focos_ano.geometry.distance(conflitos_anuais_geom[ano]).values

        # Extração do nível de conflito sob cada foco de calor
        for idx, row in focos_ano.iterrows():
            pt = ee.Geometry.Point([row['lon'], row['lat']])
            val = img_conflito.reduceRegion(ee.Reducer.first(), pt, 30).getInfo().get('conflito')
            gdf_focos_metrico.at[idx, 'conflito_local'] = val if val is not None else 0

# Classificação das distâncias para análise de gradiente
def categorizar_distancia(d):
    if pd.isna(d): return np.nan
    if d == 0: return 'Dentro do conflito'
    for v in distancias_buffer:
        if d <= v: return '0–100 m' if v == 100 else f'{v-100}–{v} m'
    return '>1000 m'

gdf_focos_metrico['classe_distancia'] = gdf_focos_metrico['distancia_conflito_m'].apply(categorizar_distancia)

# ============================================================
# 6. ESTATÍSTICAS E DENSIDADE DE FOCOS
# ============================================================
df_areas = pd.DataFrame(areas_aneis_anuais).groupby('classe')['area_km2'].mean().reset_index()
freq_focos = gdf_focos_metrico['classe_distancia'].value_counts().reset_index()
freq_focos.columns = ['classe', 'numero_focos']

df_gradiente = freq_focos.merge(df_areas, on='classe', how='inner')
df_gradiente['densidade_focos_km2'] = df_gradiente['numero_focos'] / df_gradiente['area_km2']

# Representação numérica das classes para correlação (ponto médio do buffer)
dist_rep = {'Dentro do conflito': 0, '0–100 m': 50, '100–200 m': 150, '200–300 m': 250, '300–400 m': 350,
            '400–500 m': 450, '500–600 m': 550, '600–700 m': 650, '700–800 m': 750, '800–900 m': 850, '900–1000 m': 950}

df_corr = df_gradiente.copy()
df_corr['dist_m'] = df_corr['classe'].map(dist_rep)
df_corr = df_corr.dropna(subset=['dist_m']).sort_values('dist_m')

# Testes de Correlação (Pearson e Spearman)
pearson_r, pearson_p = pearsonr(df_corr['dist_m'], df_corr['densidade_focos_km2'])
spearman_rho, spearman_p = spearmanr(df_corr['dist_m'], df_corr['densidade_focos_km2'])

print("\n--- Resultados Estatísticos (Gradiente de Distância) ---")
print(f"Correlação de Pearson : r = {pearson_r:.3f}, p = {pearson_p:.4f}")
print(f"Correlação de Spearman: rho = {spearman_rho:.3f}, p = {spearman_p:.4f}")

# ============================================================
# 7. DADOS CLIMÁTICOS: PRECIPITAÇÃO (CHIRPS) E FOCOS
# ============================================================
chirps = ee.ImageCollection('UCSB-CHG/CHIRPS/DAILY').select('precipitation')
dados_climaticos = []

for ano in anos_estudo:
    inicio = ee.Date.fromYMD(ano, 1, 1)
    fim = inicio.advance(1, 'year')
    precip_img = chirps.filterDate(inicio, fim).sum()
    media_bacia = precip_img.reduceRegion(ee.Reducer.mean(), area_estudo.geometry(), 5500).getInfo().get('precipitation')
    focos_ano = len(gdf_focos_metrico[gdf_focos_metrico['ano'] == ano])
    dados_climaticos.append({'ano': ano, 'precipitacao_mm': media_bacia or 0, 'focos': focos_ano})

df_clima = pd.DataFrame(dados_climaticos)

# ============================================================
# 8. GERAÇÃO DOS PRINCIPAIS PRODUTOS VISUAIS
# ============================================================
# Figura: Gradiente de Densidade
fig1, ax1 = plt.subplots(figsize=(8, 5))
ax1.plot(df_corr['dist_m'], df_corr['densidade_focos_km2'], marker='o', linestyle='-', color='black')
ax1.set_xlabel('Distância às áreas de conflito (m)')
ax1.set_ylabel('Densidade de focos (focos/km²)')
ax1.set_xticks(df_corr['dist_m'])
ax1.grid(axis='y', linestyle='--', alpha=0.5)
fig1.savefig(DIRETORIO_SAIDA / 'grafico_gradiente_densidade.png', dpi=300, bbox_inches='tight')

# Figura: Precipitação vs Focos de Calor
fig2, ax2 = plt.subplots(figsize=(8, 5))
l1 = ax2.plot(df_clima['ano'], df_clima['focos'], marker='o', color='#d73027', label='Focos de Calor')
ax2.set_xlabel('Ano')
ax2.set_ylabel('Número de Focos', color='#d73027')
ax3 = ax2.twinx()
l2 = ax3.plot(df_clima['ano'], df_clima['precipitacao_mm'], marker='s', color='#4575b4', label='Precipitação')
ax3.set_ylabel('Precipitação Anual (mm)', color='#4575b4')
ax2.set_xticks(df_clima['ano'])
ax2.legend(l1 + l2, [l.get_label() for l in l1 + l2], loc='upper right', frameon=False)
fig2.savefig(DIRETORIO_SAIDA / 'grafico_precipitacao_focos.png', dpi=300, bbox_inches='tight')

print(f"\nProcessamento concluído. Gráficos exportados para: {DIRETORIO_SAIDA}")